// const { a: x } = require("./file1.js");
// import { a } from "./node_esm/file1.mjs";
// console.log(a);
// const { a } = require("./file2.js");
// console.log(x);
// const { add } = require("./add");
// const { subs } = require("./subs");
// const { add, subs } = require("./node");
import node_esm from "./node_esm/index.mjs";
console.log(node_esm.add(2, 4));
console.log(node_esm.subs(2, 4));
